# Generated by Django 2.0.5 on 2018-05-24 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0003_personalboomark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalBoomark',
            new_name='PersonalBookmark',
        ),
    ]
